### ISSUE TITLE
Stop expand when reach end.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula-graph#1019]
**Is your feature request related to a problem? Please describe.**
Go/Subgraph/Match don't stop expand when reach end node.
From https://discuss.nebula-graph.com.cn/t/topic/3882

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Shylock-Hg** [comment]
1. The subgraph will collect the empty expand result, so need more discussion.

**Comment by CPWstatic** [comment]
Thanks, it seems you had solved the problem, i'll close this issue.
