### ISSUE TITLE
Some miscellaneous

### ISSUE THREAD

**Issue by zzl200012** [vesoft-inc/nebula-graph#1028]
Sorry for my disturbing. I'm a student, and I really wanna participate in the development of nebula, but now I have some troubles while learning the project. Besides, I'm also planning to apply for the [ospp](https://summer.iscas.ac.cn) program instructed by @jievince (add rules for RBO & CBO investigation). I've sent an e-mail but didn't receive a reply after a day, so I'll really appreciate it if I could get in touch with the mentor @jievince. Sorry again for my bothering!

**Comment by wey-gu** [comment]
Dear @zzl200012 ,
I am so very glad you are interested in nebula! We will reach out to you soon!
Thanks!

**Comment by jievince** [comment]
Sorry to notice your email just now, I have already replied to you

**Comment by zzl200012** [comment]
Thx, I got it! I'll close this issue.
