### ISSUE TITLE
After Add Hosts to Nebula 2.0,the leader metad instance will have different meta data when scheduled to different nodes 

### ISSUE THREAD

**Issue by turtlebin** [vesoft-inc/nebula-graph#1041]
* Nebula version : 2.0.1
* Deployment : K8S
* Description :
     I deploy a Nebula cluster with k8s, after a series of operations like snapshot create, space create, space drop, host add(when I add host, the graphd, metad, storaged instance count changes from 3 to 5), data balance, and I found a fatal problem.
    When I restart the cluster, the leader metad instance will be scheduled to different nodes, and it will have different metadata when it was scheduled to the old nodes and the newly added nodes. 
    For example, when the leader metad instance is scheduled to the old nodes, it will have a space named A with space id 1, then when I restart the cluster and the leader metad instance is scheduled to the new nodes, it will have a space named B with space id 1 as well. And both spaces A and B share the storage data path under the directory ./data/storage/nebula/1/, both spaces have data but don’t have the same amount. 
    I have no idea how can this problem occur and I can't reproduce this phenomenon, but the aforesaid problems do exist.

**Comment by wey-gu** [comment]
Dear @turtlebin,

If I guess it correctly, this is the issue reported here: https://discuss.nebula-graph.com.cn/t/topic/4011 in the forum right?
That is, deployed with Helm.

**Comment by turtlebin** [comment]
> Dear @turtlebin,
> 
> If I guess it correctly, this is the issue reported here: https://discuss.nebula-graph.com.cn/t/topic/4011 in the forum right?
> That is, deployed with Helm.

Yes，this is another issue commited in Chinese，I have no idea how can this problem occur.

**Comment by wey-gu** [comment]
@MegaByte875 is replying you via the forum :-)

**Comment by turtlebin** [comment]
> @MegaByte875 is replying you via the forum :-)

I have written a test process to reproduce the problem above in the forum  https://discuss.nebula-graph.com.cn/t/topic/4011. Hope that you can provide  a precious suggestion.

**Comment by wey-gu** [comment]
closed as answered via forum
