### ISSUE TITLE
Unify the timezone config in server side and the client can get the timezone.

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula-graph#1063]

**Comment by laura-ding** [comment]
Need to define the format of timezone, it should be universal, not just used by Linux. such as "+08:00". Because the client will run on all system platforms.

**Comment by Shylock-Hg** [comment]
> Need to define the format of timezone, it should be universal, not just used by Linux. such as "+08:00". Because the client will run on all system platforms.

I think the client don't need to set timezone. It just get timezone information from server.

**Comment by Shylock-Hg** [comment]
Get the timezone name(optional) and timezone offset (second) from server.

**Comment by Shylock-Hg** [comment]
Why does client need this?
