### ISSUE TITLE
-v does not return version information

### ISSUE THREAD

**Issue by study-day** [vesoft-inc/nebula-graph#1066]
**Please check the FAQ documentation before raising an issue**

Please check the [FAQ](https://github.com/vesoft-inc/nebula/blob/master/docs/manual-EN/1.overview/2.quick-start/2.FAQ.md) documentation and old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: Linux hadoop-node-2 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Compliler: `g++ --version` or `clang++ --version`
* CPU: `Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:              7
CPU MHz:               1136.663
CPU max MHz:           3900.0000
CPU min MHz:           1000.0000
BogoMIPS:              4600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15,32-47
NUMA node1 CPU(s):     16-31,48-63
Flags:      `
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

```
[nebula@hadoop-node-4 scripts]$ ./nebula.service -v status all
[INFO] nebula-metad: Exited
[INFO] nebula-graphd: Exited
[INFO] nebula-storaged: Exited
[nebula@hadoop-node-4 scripts]$ ./nebula.service -v
Usage: ./nebula.service [-v] [-c /path/to/config] <start|stop|restart|status|kill> <metad|graphd|storaged|all>

```
Just upgraded to 2.0.1

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by Aiee** [comment]
To check the version of nebula service, run `./bin/nebula-graphd --version`

**Comment by study-day** [comment]
That's good, it is recommended to modify the command prompt

**Comment by wey-gu** [comment]
> That's good, it is recommended to modify the command prompt

Sorry for the confusion, the `-v` in the service scripts stands for the option of output in VERBOSE level.

**Comment by Aiee** [comment]
> > That's good, it is recommended to modify the command prompt
> 
> Sorry for the confusion, the `-v` in the service scripts stands for the option of output in VERBOSE level.

Actually, binary files are used to check version info instead of service scripts. I believe this change is doable.

**Comment by wey-gu** [comment]
> > > That's good, it is recommended to modify the command prompt
> > 
> > 
> > Sorry for the confusion, the `-v` in the service scripts stands for the option of output in VERBOSE level.
> 
> Actually, binary files are used to check version info instead of service scripts. I believe this change is doable.

agreed, this should be improved, maybe something like the daemon binary(binaries) version(s) to be returned in a service status query or from a new query option?
