### ISSUE TITLE
不定长路径查询是否不支持

### ISSUE THREAD

**Issue by daqin666** [vesoft-inc/nebula-graph#1076]
match p=(:test_nd)-[:follow*]-(:test_nd{name:'Tom'}) return p;

类似这种想要查询出指向Tom的所有路径，目前nebula支持吗，如何实现

**Comment by wey-gu** [comment]
Dear @daqin666,
I transferred this issue to nebula-graph from nebula-graph-studio.

For Match with Variable-length please refer to graph-pattern in docs:

https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/1.nGQL-overview/3.graph-patterns/#_7

BR//Wey

**Comment by daqin666** [comment]
文档中“必须指定最大长度，不支持仅指定最小长度（(a)-[*3..]->(b)）或都不指定（(a)-[*]->(b)）”，这句话是不是意味着暂时还不支持这种不知道最大长度的查询语句，后续会支持这种语句吗，因为我想往前溯源到所有的数据，但是我不知道长度究竟是多长，也不知道起始节点的相关信息。

**Comment by daqin666** [comment]
文档中“必须指定最大长度，不支持仅指定最小长度（(a)-[*3..]->(b)）或都不指定（(a)-[*]->(b)）”，这句话是不是意味着暂时还不支持这种不知道最大长度的查询语句，后续会支持这种语句吗，因为我想往前溯源到所有的数据，但是我不知道长度究竟是多长，也不知道起始节点的相关信息。

**Comment by wey-gu** [comment]
Dear @daqin666 
could you check if `find path` / `get subgraph` fulfills your requirement now?
If starting vid is known:
https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/16.subgraph-and-path/2.find-path/

If starting vid is unknown:
https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/16.subgraph-and-path/1.get-subgraph/

**Comment by daqin666** [comment]
GET SUBGRAPH语句中如果我不知道步长step_count的是多少的话，是不是该语句就无法使用，我想查询到所有步长的数据但是我不知道步长是多少，而且该语句的step_count写的越大，性能似乎越差，我自己创建的关系，只有3步长，但是我写了一个很大的步长，结果nebula-graph服务exited了，按逻辑应该查完三个步长的数据之后，该停止查询了；另外FIND PATH语句后续能否支持只知道起始节点vid，不知道结束节点vid的查询呢。

**Comment by wey-gu** [comment]
> GET SUBGRAPH语句中如果我不知道步长step_count的是多少的话，是不是该语句就无法使用，我想查询到所有步长的数据但是我不知道步长是多少，而且该语句的step_count写的越大，性能似乎越差，我自己创建的关系，只有3步长，但是我写了一个很大的步长，结果nebula-graph服务exited了，按逻辑应该查完三个步长的数据之后，该停止查询了；另外FIND PATH语句后续能否支持只知道起始节点vid，不知道结束节点vid的查询呢。

抱歉回复晚了
> GET SUBGRAPH语句中如果我不知道步长step_count的是多少的话，是不是该语句就无法使用
不是的 中括号里的部分`[<step_count> STEPS]` 是可选的哈，您可以不写 STEPS的。

> FIND PATH语句后续能否支持只知道起始节点vid，不知道结束节点vid的查询呢。
这个情况更符合 GO 的query吧？不能满足您的需求么？

另外，您可以来论坛中文提问的 https://discuss.nebula-graph.com.cn/ 工作时间几个小时内一定会有回复的。

**Comment by daqin666** [comment]
好的，十分感谢您的答复！
