### ISSUE TITLE
Confusion caused by “show tag indexes” and "show tag index status"  

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula-graph#1090]
<img width="450" alt="showtagindexes" src="https://user-images.githubusercontent.com/84314746/119925278-b9a56500-bfa7-11eb-963a-131c8406be68.png">
When 'show tag indexes' statement is executed, two records are displayed.But when 'show tag indexes' statement is executed, one record is displayed.

**Comment by bright-starry-sky** [comment]
“Show tag index status” means index rebuild status.
