### ISSUE TITLE
LOOKUP fails and says No valid index found but there are indexes

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#1093]
LOOKUP statement fails and says No valid index found, but there are indexes.

nGQL: LOOKUP ON player WHERE player.name == "Tim Duncan" AND player.age > 30 YIELD player.name, player.age;

![image](https://user-images.githubusercontent.com/69501902/119960407-811d7f80-bfd7-11eb-8b3f-a34eaff6922d.png)

**Comment by yixinglu** [comment]
duplicate with #1039

**Comment by bright-starry-sky** [comment]
`AND` operation for multiple indexes are not supported.
You could create index (name, age)
