### ISSUE TITLE
Find path between two vertex over edges with specific attribute 

### ISSUE THREAD

**Issue by hamidehhhs** [vesoft-inc/nebula-graph#1102]
I have create a graph that some attributes on its edges. 
I am wondering to find path between two vertex over edges filtered on its attribute. 
To do so I try this query
FIND ALL PATH FROM  <vertex_id1> TO  <vertex_id2> OVER edge.attribute1 == "text";

but I faced 'SyntaxError'

Is it possible to  filter edges with attribute on path queries?

**Comment by wey-gu** [comment]
Dear @hamidehhhs ,


```
FIND ALL PATH FROM <vertex_id1> TO <vertex_id2> OVER edge;

```

**Comment by wey-gu** [comment]
Dear @hamidehhhs , 

Also, thanks to @nevermore3 , the PR(https://github.com/vesoft-inc/nebula-graph/pull/1091) to support WHERE CLAUSE is WIP.

BR//Wey

**Comment by hamidehhhs** [comment]
Dear @wey-gu 

Thanks for your reply. So you mean now it is possible to filter  edges attributes  in find path algorithms now ?

**Comment by wey-gu** [comment]
> Dear @wey-gu
> 
> Thanks for your reply. So you mean now it is possible to filter edges attributes in find path algorithms now ?

Dear @hamidehhhs, sorry I meant it's not yet ready but is working in progress.

**Comment by wey-gu** [comment]
update:
- property filter in edge: merged https://github.com/vesoft-inc/nebula-graph/pull/1091
- property filter in vertex: will be started https://github.com/vesoft-inc/nebula-graph/issues/1128

**Comment by CPWstatic** [comment]
I'll close it first since we had another related issues. Now we have support for filtering the paths through edge properties, hope it is helpful for you.
