### ISSUE TITLE
Metrics for session numbers

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-graph#1107]
**Is your feature request related to a problem? Please describe.**
One of our users asked me about this, which reminded me that, we should have this observability on session numbers to avoid it accumulated or raised in an unexpected trend.

**Describe the solution you'd like**
Provide such metrics.

**Describe alternatives you've considered**
Or could be queried via ngql?

**Additional context**
As mentioned in first section.
Talking with @cangchen8180 .

**Comment by cangchen8180** [comment]
每个graphd当前active的session数（有clientip 创建时间等信息更好）；
服务器建立过的session总数；
主动过期的session个数

session的上限；

session占用的资源情况

**Comment by CPWstatic** [comment]
Now you can call `show sessions` to get the total sessions.
