### ISSUE TITLE
DBA role can not rebuild index 

### ISSUE THREAD

**Issue by zhoupengbo** [vesoft-inc/nebula-graph#1122]
DBA role can not rebuild index ,  errors: 
PermissionError: No Permission to write space . 
why need write space access?

nebula version 2.0.1

**Comment by bright-starry-sky** [comment]
Good issue,  I agree with your suggestion, guess is that all AdminJobs are treated as God permissions. Let's break it down further and allow admin permissions on the following items.

```
case meta::cpp2::AdminCmd::REBUILD_TAG_INDEX:
case meta::cpp2::AdminCmd::REBUILD_EDGE_INDEX:
case meta::cpp2::AdminCmd::REBUILD_FULLTEXT_INDEX:
case meta::cpp2::AdminCmd::STATS:
case meta::cpp2::AdminCmd::COMPACT:
case meta::cpp2::AdminCmd::FLUSH:
```

**Comment by zhoupengbo** [comment]
> Good issue, I agree with your suggestion, guess is that all AdminJobs are treated as God permissions. Let's break it down further and allow admin permissions on the following items.
> 
> ```
> case meta::cpp2::AdminCmd::REBUILD_TAG_INDEX:
> case meta::cpp2::AdminCmd::REBUILD_EDGE_INDEX:
> case meta::cpp2::AdminCmd::REBUILD_FULLTEXT_INDEX:
> case meta::cpp2::AdminCmd::STATS:
> case meta::cpp2::AdminCmd::COMPACT:
> case meta::cpp2::AdminCmd::FLUSH:
> ```

thank you!

**Comment by Shylock-Hg** [comment]
> Good issue, I agree with your suggestion, guess is that all AdminJobs are treated as God permissions. Let's break it down further and allow admin permissions on the following items.
> 
> ```
> case meta::cpp2::AdminCmd::REBUILD_TAG_INDEX:
> case meta::cpp2::AdminCmd::REBUILD_EDGE_INDEX:
> case meta::cpp2::AdminCmd::REBUILD_FULLTEXT_INDEX:
> case meta::cpp2::AdminCmd::STATS:
> case meta::cpp2::AdminCmd::COMPACT:
> case meta::cpp2::AdminCmd::FLUSH:
> ```

I think it's ok. Only the balance need write space permission in fact, the others only need write data permission. How do you think?

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
