### ISSUE TITLE
Nebula-2.0.0-ga的复合索引使用体验, 小建议

### ISSUE THREAD

**Issue by yangmeng66** [vesoft-inc/nebula-graph#1124]
你好, Nebula 
     对于目前2.0.0版本的复合索引, 目前使用下来的话, 整体感觉没有常规的(只建立单个索引就可以and复合查询)方便,  是有什么原因不能做成常规的索引吗?  因为在实际场景中一个tag可能有几十个属性, 查询是很灵活的
相关Nebula论坛: https://discuss.nebula-graph.com.cn/t/topic/2501  https://discuss.nebula-graph.com.cn/t/topic/4306/14   

谢谢!

**Comment by bright-starry-sky** [comment]
Thank you for your advice, we will discuss it offline later and make further optimization.

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
