### ISSUE TITLE
Nebula Graph 支持属性为list吗？

### ISSUE THREAD

**Issue by sataliulan** [vesoft-inc/nebula-graph#1156]
我现在要用Nebula Exchange 将数据从neo4j导入nebula Graph 2.0.1, 发现neo4j中某个节点的属性为list类型，我尝试在nebula graph中创建对应的属性，却发现找不到对应的数据类型。我看文档上说Nebula Graph中的属性也是Key Value pair，这里的value不可以为list么？若不支持list属性值，我又该如何处理呢？

**Comment by Shylock-Hg** [comment]
Can't set the property type to List.
Maybe you could encode it to string.

**Comment by sataliulan** [comment]
thx，Done just like you said
