### ISSUE TITLE
using EMPTY exception in match statement

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula-graph#1158]
Judging by a nonexistent property, it is said that all points should be returned.
MATCH (v:player) WHERE v.nadsaesa IS  EMPTY return v;  
![image](https://user-images.githubusercontent.com/78672629/122725437-92d90680-d2a7-11eb-9f10-cc22a3cf8a4b.png)

This is to determine whether V2 has an age property. Normally, the team point should be filtered out.
MATCH (v:player)--(v2) WHERE v2.age IS NOT EMPTY RETURN labels(v2)  
![image](https://user-images.githubusercontent.com/78672629/122725520-a97f5d80-d2a7-11eb-9dd3-b2148a4e0beb.png)

**Comment by CPWstatic** [comment]
`IS NOT EMPTY` in where clause is applied to the result. That means the result  in the 2nd picture is within our expectations. We could use `exists` in such a situation.
```
MATCH ... WHERE exists(v2.age) RETURN labels(v2)
```
