### ISSUE TITLE
希望在创建图空间语句的vid_type里面增加一个新的类型UINT64

### ISSUE THREAD

**Issue by sunwhite33** [vesoft-inc/nebula-graph#1178]
用nGQL命令创建一个图空间的语句是：create space test (vid_type=INT64)，这里的vid_type是有符合的64位整数，但我需要的是无符号的64位整数，类似UINT64，因为有符号整数所表达的数值范围不够，希望能增加一个新的类型UINT64表示为无符号的64位整数。当然我的这个需求也可以用FIXED_STRING解决，但我更希望的是直接使用整数类型的表达方式，希望可以在未来的版本中实现这个需求。谢谢！

nebula 版本：2.0.01

**Comment by czpmango** [comment]
目前可以尝试在导入数据前把 uint64 转换为 int64，比如把超过 int64_t::max() 的值映射到负数域。
后续可能增加对 uint64 vid 的支持，但优先级不高，因为大多数场景下 int64 已经够用了。

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
