### ISSUE TITLE
kill successfully displays unknown error

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula-graph#1203]
![image](https://user-images.githubusercontent.com/78672629/124443418-3e0db380-ddb0-11eb-85d8-d29893098262.png)
![image](https://user-images.githubusercontent.com/78672629/124443430-41a13a80-ddb0-11eb-827c-6e17c33eec2b.png)

**Comment by CPWstatic** [comment]
We had fix it, please let us know if we have solved your problem.

**Comment by cooper-lzy** [comment]
Yes, it has been solved.
