### ISSUE TITLE
i want to export  privileges data only 

### ISSUE THREAD

**Issue by riverzzz** [vesoft-inc/nebula-graph#1231]
# Summary

i want to export privileges data only.

# Motivation

i create a new cluster and i change space partitions,so i do not need data info.but  i have grant privilege to too many users in old cluster,so i want to export privileges data or privileges sql.

**Comment by Shylock-Hg** [comment]
I think you could it now already.
1. `show spaces` to get all spaces
2. `show create space <>` to get query to create space
3.  `show users` to get all users
4. `show roles in <>` to get all permission in space, then you could assemble the grant query.

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
