### ISSUE TITLE
How to join the slack channel ?

### ISSUE THREAD

**Issue by jackwener** [vesoft-inc/nebula-graph#1262]
the link of slack channel in readme is just a home page.
How do I get invitation from administrator

**Comment by jackwener** [comment]
Maybe there is a problem in the link?
It is should be the invitation page instead of home page.

**Comment by wey-gu** [comment]
> Maybe there is a problem in the link?
> It is should be the invitation page instead of home page.

Dear @jackwener , thanks!!

Could you help check if [this link](https://join.slack.com/t/nebulagraph/shared_invite/zt-7ybejuqa-NCZBroh~PCh66d9kOQj45g) works for you?
