### ISSUE TITLE
expression/function to get degrees

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-graph#1285]
**Is your feature request related to a problem? Please describe.**
To have the semantic to get in/out degrees per vertex.

**Describe the solution you'd like**
Maybe `indegree` or `outdegree` as mentioned by @yixinglu.

**Describe alternatives you've considered**
Or something more `OpenCypher` cc @whitewum 

**Additional context**
https://discuss.nebula-graph.com.cn/t/topic/4947

**Comment by Shylock-Hg** [comment]
We could consider the form `$a = go from 'Tim Duncan' over *; yield size($a);`, it's not workable now.
