### ISSUE TITLE
Multiline ngql isn't supported.

### ISSUE THREAD

**Issue by jackwener** [vesoft-inc/nebula-graph#1290]
**Is your feature request related to a problem? Please describe.**
```
> CREATE TAG IF NOT EXISTS user(
[ERROR (-7)]: SyntaxError: syntax error near `('
```

**Describe the solution you'd like**
It can be supported

**Comment by Shylock-Hg** [comment]
You should use `\` to escape the line break. e.g. `CREATE TAG IF NOT EXISTS user(\`
