### ISSUE TITLE
count, avg, sum support condition filter

### ISSUE THREAD

**Issue by blacklovebear** [vesoft-inc/nebula-graph#1320]
* current problem
count (age>30) no effect. The result just same with count(*)
![355474d627ac0b7664469968caa1209](https://user-images.githubusercontent.com/5400147/129690740-81aa7ff9-4de7-4bac-ab49-0417b7c820cc.png)

* want result
age, sex
10, M
20, F
30, F
40, M

count(age>20) return 2, count(sex == 'M') return 2

**Comment by czpmango** [comment]
```
RETURN count(case when age>20 then true end)
```
