### ISSUE TITLE
SHOW ALL QUERIES shows nothing

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#1333]
Nebula Graph version: 2.5.0

`SHOW ALL QUERIES` is supposed to show queries in all sessions, right? But it shows nothing. Tested on different client hosts.

![image](https://user-images.githubusercontent.com/69501902/130052426-6d8cd1d1-a7a4-445f-bd27-bc46324eedc2.png)

![image](https://user-images.githubusercontent.com/69501902/130052370-f665f335-3d58-4d6a-b0c4-913c57bac73c.png)

**Comment by randomJoe211** [comment]
OK, I found that `SHOW QUERIES` and `SHOW ALL QUERIES` only show the running queries. The keywords used are very misleading. In the English language, show all queries clearly means showing all queries, running or not. Even it cannot show all query history since the services start, I thought it could at least show the queries executed in all active sessions, but it can't.

Please consider optimizing the keywords.

**Comment by whitewum** [comment]
Just let it be. 

And please change the doc accordingly.
