### ISSUE TITLE
`toLower()` does not support in `lookup`

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula-graph#1335]
In Nebula Graph version v2.5.0, the following statement is not supported:
```
(root@nebula) [basketballplayer]> LOOKUP ON player WHERE player.name CONTAINS toLower("L") \
                               ->         YIELD player.name, player.age;
[ERROR (-1009)]: SemanticError: Expression (player.name CONTAINS toLower("L")) not supported yet
```
But in the previous version, the statement has a return value as follows:
```
nebula> LOOKUP ON player WHERE player.name CONTAINS toLower("L") \
        YIELD player.name, player.age;
+-------------+---------------------+------------+
| VertexID    | player.name         | player.age |
+-------------+---------------------+------------+
| "player145" | "JaVale McGee"      | 31         |
+-------------+---------------------+------------+
| "player144" | "Shaquille O'Neal"  | 47         |
+-------------+---------------------+------------+
| "player102" | "LaMarcus Aldridge" | 33         |
+-------------+---------------------+------------+
```

**Comment by Aiee** [comment]
This case has been added in [this pr](https://github.com/vesoft-inc/nebula-graph/pull/1251/files#diff-593c691acd0611750cea4018240e111363ce5b7e074f9a6a378ce877ea8574f7R238-R259). It's weird if this is not supported in the master branch. Could you verify the version of Nebula service?

**Comment by whitewum** [comment]
show the graph version

**Comment by bright-starry-sky** [comment]
I don't agree to support this syntax. This syntax will result in a full index scan. It's a departure from our original design.

**Comment by bright-starry-sky** [comment]
If there is such a need, it is best to use full-text index.

**Comment by whitewum** [comment]
There must be something wrong with the developing, testing and releasing process.

**Comment by foesa-yang** [comment]
![截屏2021-08-20 上午10 33 48](https://user-images.githubusercontent.com/35463247/130170099-a4541e4b-b522-4890-86ca-8785c6233292.png)

**Comment by czpmango** [comment]
> I don't agree to support this syntax. This syntax will result in a full index scan. It's a departure from our original design.

`lookup on player` also result in a full tag scan. Should we disable these scenarios?

**Comment by whitewum** [comment]
@Sophie-Xie loop PM

**Comment by Aiee** [comment]
@whitewum In the off-line discussion with @bright-starry-sky , he states that this scenario should be processed using full-text search, since this query triggers a full index scan, and will potentially result in a slow query. @bright-starry-sky also talked about this with Sherman, and they had an agreement on this.

So we decide to not support this kind of filter, and I will refactor this PR and submit it to the nebula repo.

**Comment by whitewum** [comment]
@Sophie-Xie is it proper to add to change log in release note?
