### ISSUE TITLE
Picture of logo in readme is broken

### ISSUE THREAD

**Issue by jackwener** [vesoft-inc/nebula-graph#1343]
**Summary**

Picture of logo in readme is broken

**Comment by wey-gu** [comment]
Thank you @jackwener !
Harris is helping with this in https://github.com/vesoft-inc/nebula-graph/pull/1319

**Comment by jackwener** [comment]
I will remain the issue for avoiding redundant issue until it merge.
Maybe, It could be improved  about `Linked pull requests` and more tag.
