### ISSUE TITLE
The property order of the returned results has changed

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula-graph#1345]
In the schema, name comes first and age comes second, but the order in the returned result is wrong.

![image](https://user-images.githubusercontent.com/78672629/130725257-5ef70359-68f8-40e2-b7ce-df0a71de78a7.png)

**Comment by whitewum** [comment]
I checked opencypher specification and tck tests. And I also googled. Very few about this behavior.

``` 
# a tck case about add property
  Scenario: Overwrite values when using +=
    Given an empty graph
    And having executed:
      """
      CREATE (:X {name: 'A', name2: 'B'})
      """
    When executing query:
      """
      MATCH (n:X {name: 'A'})
      SET n += {name2: 'C'}
      RETURN n
      """
    Then the result should be, in any order:
      | n                             |
      | (:X {name: 'A', name2: 'C'}) |
    And the side effects should be:
      | +properties | 1 |
      | -properties | 1 |
```

My suggestion is to clarify that: `Properties have no guaranteed order` in the doc.

**Comment by CPWstatic** [comment]
Thanks for taking care of this. The opencypher do not specify such a behavior, and i think there would not be one of such a specification. As said by @whitewum , we implement the map by an `unordered map`, the order would not be guaranteed. As far as i know, this is not a big problem for using. So i'll close this issue first unless we really meet any using problems in real world.
