### ISSUE TITLE
MATCH p=(v)-[e:tick_change*1..2]-(v2) WHERE id(v) IN ["482680108"] AND e.day==20210823 return p; return Empty set

### ISSUE THREAD

**Issue by ttkyl** [vesoft-inc/nebula-graph#1347]
MATCH:
MATCH p=(v)-[e:tick_change]-(v2) WHERE id(v) IN ["482680108"] AND e.day>20210823 return p;
![image](https://user-images.githubusercontent.com/79440350/131126791-b13e22d3-f155-40bc-b419-b399e18f0b3e.png)

it works well.

But
MATCH p=(v)-[e:tick_change*1..2]-(v2) WHERE id(v) IN ["482680108"] AND e.day>20210823 return p;
Empty set

How to use MATCH query variable-length AND filter edge properties(such e.day>20210823)

**Comment by CPWstatic** [comment]
```
id(v) IN ["482680108"] AND all(n in e where n.day>20210823)
```
