### ISSUE TITLE
Go FROM query command，There is no way to tell which point is the beginning or end of the edge

### ISSUE THREAD

**Issue by ttkyl** [vesoft-inc/nebula-graph#1348]
GO 1 To 2 STEPS FROM "482680108" OVER tick_change  BIDIRECT WHERE tick_change.day>=20210823 AND tick_change.day<=20210823 YIELD DISTINCT tick_change._src AS src,tick_change._dst AS dst,tick_change.nums AS nums,tick_change.day as day,tick_change.cnt as cnt,tick_change.total_cost AS cost,tick_change.total_win AS win,"tick_change" AS tagname

![image](https://user-images.githubusercontent.com/79440350/131127455-98e06d78-5e40-4946-914d-79e63ede793b.png)
![image](https://user-images.githubusercontent.com/79440350/131127525-f671818c-2fe3-448d-9af2-423ade1572b5.png)

The relationship between these two edges is actually 482680108->(nums:20)->522902110. 522902110->(NUMS :20)-> 482680108, but there is no way to determine.
How should you write the go from command？

**Comment by wey-gu** [comment]
try this: 
`tick_change._type`  > 0 means src -> dst and < 0 vise versa.

```ngql
GO 1 To 2 STEPS FROM "482680108" OVER tick_change BIDIRECT YIELD tick_change._type
```
