### ISSUE TITLE
Alter User to change default root password not working

### ISSUE THREAD

**Issue by Jayuda** [vesoft-inc/nebula-graph#1360]
Hello guys, i have create docker nebula with nebula-up. And i access this database with nebula studio. Everything work well  create space, node, etc. 
But i want to change default password for user root with nGQL : 
```
ALTER USER root WITH PASSWORD 'NerwPassword';
```
Show success result with green notifications.
![image](https://user-images.githubusercontent.com/1973447/154025204-84b1c135-0314-4398-a83a-35782f234cca.png)

For check this, i am logout and login again with user = root and pass = nebula --> Still success login and password valid.
Any clue about it ?

**Comment by wey-gu** [comment]
Dear @Jayuda,
This repo is archived actually, vesoft-inc/nebula is the repo for nebula core.

This is related to `--enable_authorize` and in nebula-up and docker-compose, it's actually `false` due to it's not a production deployment.

ref: https://docs.nebula-graph.io/2.6.2/7.data-security/1.authentication/1.authentication/

**Comment by Jayuda** [comment]
I have change /usr/local/nebula/etc/nebula-graphd.conf parameter --enable_authorize=true 
and restart graphd. 
after that i cant login anymore with user root and password nebula.

How to set it ?

**Comment by wey-gu** [comment]
> I have change /usr/local/nebula/etc/nebula-graphd.conf parameter --enable_authorize=true and restart graphd. after that i cant login anymore with user root and password nebula.
> 
> How to set it ?

In docker-compose deployed nebula graph, the conf was passed with the run command through docker-compose.yaml file

ref: https://docs.nebula-graph.io/3.0.0/5.configurations-and-logs/1.configurations/1.configurations/#configuration_files_for_clusters_installed_with_docker_compose

**Comment by Jayuda** [comment]
thank you for your answer and patience Mr. @wey-gu 
Work well

**Comment by wey-gu** [comment]
Any time @Jayuda :)
