### ISSUE TITLE
The document link on the homepage is invalid

### ISSUE THREAD

**Issue by Shinji-IkariG** [vesoft-inc/nebula-graph#221]
Document URL is invalid
![图片](https://user-images.githubusercontent.com/58841610/90477454-0416cd00-e15e-11ea-86d6-2041cf1c5b8c.png)

![图片](https://user-images.githubusercontent.com/58841610/90479504-5f968a00-e161-11ea-91d6-a91e97637e18.png)

**Comment by jievince** [comment]
It's ok now.
