### ISSUE TITLE
I don’t understand the  query results 

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-graph#229]
![image](https://user-images.githubusercontent.com/42762957/90609286-66db9780-e236-11ea-89b6-b0bb931ba0dc.png)
What does the `null ` column mean here

**Comment by Shylock-Hg** [comment]
Maybe `Nullable`?

**Comment by laura-ding** [comment]
@Amber1990Zhang It is recommended to use MySQL firstly.
