### ISSUE TITLE
Query returns incorrect result

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula-graph#335]
query1: ```GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $$.player.name```
query2: ```GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $^.player.name```

Description: query1 is able to fetch 1 vertex but query2 returns an empty set as shown below. The only difference between these 2 queries is that the first one YIELD a destination vertex while the second TIELD the starting vertex, and as a consequence query2 should return the starting vertex instead of an empty set.

This might be caused by the incorrect implementation of IN expression.
```
(root@nebula) [nba]> GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $$.player.name
+----------------+
| $$.player.name |
+----------------+
| Tim Duncan     |
+----------------+
Got 1 rows (time spent 2668/2969 us)
Wed, 14 Oct 2020 19:44:41 CST
(root@nebula) [nba]> GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $^.player.name
Empty set (time spent 1226/1590 us)
```

**Comment by yixinglu** [comment]
I have checked the result in newest version of nebula graph and found not any problems now. So this issue seems to be fixed.

```
(user@nebula) [nba]> GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $$.player.name
+----------------+
| $$.player.name |
+----------------+
| "Tim Duncan"   |
+----------------+
Got 1 rows (time spent 4486/4943 us)

Thu, 20 May 2021 13:44:48 CST

(user@nebula) [nba]>  GO FROM 'Tony Parker' OVER like WHERE like._dst IN ['Tim Duncan', 'Danny Green'] YIELD $^.player.name
+----------------+
| $^.player.name |
+----------------+
| "Tony Parker"  |
+----------------+
Got 1 rows (time spent 2281/2796 us)

Thu, 20 May 2021 13:44:56 CST
```
