### ISSUE TITLE
About the space "none"

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#354]
By default `(root@nebula) [(none)]>` is displayed, but if we create a space named `none` and use it, the CLI still shows `(root@nebula) [(none)]>`. But they are totally different.

Shall we consider adding `none` into the reserved word list?

**Comment by yixinglu** [comment]
console will display the prefix for the space named `none` with the following format:

```
(root@nebula) [none]>
```

It is different from the case which doesn't use any space.

So I close this issue now. If you still have any problem, please call you offline.
