### ISSUE TITLE
directly support `RETURN 1+1`

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#390]
as shown:

![image](https://user-images.githubusercontent.com/50101159/97960246-0b0fbc00-1dec-11eb-8717-93c96c10457b.png)

![image](https://user-images.githubusercontent.com/50101159/98188445-f9462a00-1f4d-11eb-8a9b-2fba11889d44.png)

The openCypher 9 TCK :   `ReturnAcceptance.feature` file requests that:

```
Scenario: Arithmetic precedence with parenthesis test
    Given any graph
    When executing query:
      """
      RETURN 12 / 4 * (3 - 2 * 4)
      """
    Then the result should be, in any order:
      | 12 / 4 * (3 - 2 * 4) |
      | -15                  |
    And no side effects
```

I think the clause `RETURN 1+1` can be implemented and is reasonable (as in Match-clause).

**Comment by dutor** [comment]
Yes. I had considered this. But there is a `RETURN` statement already, which was added for some narrow purposes, which will grammatically conflict with the `RETURN` clause of cypher. We will remove that statement to address this.
