### ISSUE TITLE
Can't find the index for the second property in MATCH

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#457]
![image](https://user-images.githubusercontent.com/69501902/101140723-510baa00-364e-11eb-9684-c4bd29b0eea9.png)

Q1: I thought MATCH only needs one index, then why does it try to find the index for the 2nd property?
Q2: The age property has an index already, but why does it say no index found?

nGQL: `MATCH (v:player{name:"Tim Duncan", age:42}) -- (v2) RETURN v2.name AS Name, v2.age AS Age`

**Comment by czpmango** [comment]
The index of `name` is different from the index of `name+age`. There is no index for `name+age`.
