### ISSUE TITLE
Alias case issue

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#472]
![image](https://user-images.githubusercontent.com/69501902/101867184-83b92380-3bb5-11eb-949a-c3e71cd7a5a3.png)

In the result of 

```
MATCH p=(v:player{name:"Tim Duncan"})-[]->() RETURN p AS Path, length(p) AS Length
```
`path` is not capitalized.

If I change `Path` in the statement to other words it works.

**Comment by jievince** [comment]
It's a known bug.  When you use any keywords as an alias, this bug will appear.
