### ISSUE TITLE
SHOW CONFIGS storage error

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#486]
![image](https://user-images.githubusercontent.com/69501902/102302472-15e57100-3f94-11eb-88b2-ecbeae9be003.png)
 I can show configs of graph or meta, but not for storage.

All processes are up and running.

**Comment by randomJoe211** [comment]
![image](https://user-images.githubusercontent.com/69501902/102302700-8c826e80-3f94-11eb-964c-78b4123f9b3e.png)
version

**Comment by laura-ding** [comment]
You are supposed to be updating data from an old version to a new version, but the new version has added a new data interface, which makes it incompatible.

**Comment by laura-ding** [comment]
I have confirmed with @randomJoe211  that the old data is used, so I will close it.
