### ISSUE TITLE
SHOW CONFIS graph problems

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#487]
1. the type column shows `"__EMPTY__"`
![image](https://user-images.githubusercontent.com/69501902/102308543-ce65e180-3fa1-11eb-91d1-493ddee7845f.png)

2. In one cluster it shows `"enable_optimizer"`, but in another, it doesn't. The Nebula Graph versions are the same. And both are deployed with docker-compose.
![image](https://user-images.githubusercontent.com/69501902/102308635-0b31d880-3fa2-11eb-9af8-456d304abfa5.png)

**Comment by laura-ding** [comment]
the same as https://github.com/vesoft-inc/nebula-graph/issues/486

**Comment by laura-ding** [comment]
I have confirmed with @randomJoe211  that the old data is used, so I will close it.
