### ISSUE TITLE
an i/o timeout error

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-graph#552]
Nebula 2.0, deployed with Docker Compose.

When I ran MATCH, FIND PATH, and GET SUBGRAPH, an i/o timeout error occurred. But I can run GO and FETCH. 

I tried stopping the services, deleting the data directory, and then starting the services again. Nothing was improved. 

![image](https://user-images.githubusercontent.com/61895496/103404759-bee4bc00-4b8f-11eb-9176-3fbd8b15d6e5.png)

![image](https://user-images.githubusercontent.com/61895496/103404806-dde34e00-4b8f-11eb-9dd4-addc3c38af14.png)

![image](https://user-images.githubusercontent.com/61895496/103404827-f2274b00-4b8f-11eb-8bdb-2844bdcf184d.png)

**Comment by HarrisChu** [comment]
As we release v2.0 in Mar, could you try it in the latest version?
