### ISSUE TITLE
[openCypher compatibility] fail to use count(*) to get number of nodes in a return clause

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#574]
nGQL：MATCH (v {name: 'Tim Duncan'})-[]->(v2) RETURN labels(v), v.age, count(*)
![image](https://user-images.githubusercontent.com/69501902/104112671-b11bfd00-532c-11eb-8047-e9f7725ff23c.png)

openCypher:
![image](https://user-images.githubusercontent.com/69501902/104112678-e1fc3200-532c-11eb-96be-111947f6f2e3.png)

Conclusion: This statement should return the number of nodes, but nGQL failed to parse it.

**Comment by czpmango** [comment]
Same as [https://github.com/vesoft-inc/nebula-graph/issues/573](https://github.com/vesoft-inc/nebula-graph/issues/573)

**Comment by czpmango** [comment]
It has nothing to do with `count(*)`.
