### ISSUE TITLE
[openCypher compatibility] Fail to group and count relationship types

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#575]
nGQL: MATCH (v:player{name: 'Tim Duncan'})-[e]->() RETURN type(e), count(*)
![image](https://user-images.githubusercontent.com/69501902/104112802-18867c80-532e-11eb-8d1d-4d7b657682e0.png)

openCypher:
![image](https://user-images.githubusercontent.com/69501902/104112811-2dfba680-532e-11eb-88b8-f1a6dbfce1bc.png)

**Comment by czpmango** [comment]
Already fixed.
```
(czp@nebula) [nba]> match (v:player{name:"Tim Duncan"})-[e]->() return type(e),count(*)
+------------+----------+
| type(e)    | COUNT(*) |
+------------+----------+
| "serve"    | 1        |
+------------+----------+
| "teammate" | 4        |
+------------+----------+
| "like"     | 2        |
+------------+----------+
```
