### ISSUE TITLE
[openCypher compatibility] Fail to use count(expression) to return the number of values

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#576]
nGQL: MATCH (v:player{name: 'Tim Duncan'})-[e]->(v2) RETURN count(v2)
![image](https://user-images.githubusercontent.com/69501902/104112937-76679400-532f-11eb-9d5a-faa000c0ccc7.png)

openCypher:
![image](https://user-images.githubusercontent.com/69501902/104112944-87b0a080-532f-11eb-8779-3559486c4d8f.png)

**Comment by czpmango** [comment]
Already Fixed. @randomJoe211 
This is my test:
```
(czp@nebula) [nba]> match (v:player{name:"Tim Duncan"})-[e]-(v2) return count(v2)
+-----------+
| COUNT(v2) |
+-----------+
| 19        |
+-----------+
Got 1 rows (time spent 18427/19044 us)
```
