### ISSUE TITLE
Using id() in WHERE clause in MATCH causes the service to restart

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#584]
Every time I run `MATCH (v:player) -[e:follow]-> (v2) WHERE id(v)=="player101" RETURN v2`, the service restarts.

![image](https://user-images.githubusercontent.com/69501902/104163010-a0ed4600-5430-11eb-8956-8f3dc8c41144.png)

It seems like there is a index conflict. If I omit `:player` and do not use other indexes, it works fine. But if I use id(v) and another index together, there goes this issue.

**Comment by Shylock-Hg** [comment]
What's the version or commit id?

**Comment by randomJoe211** [comment]
> What's the version or commit id?

![image](https://user-images.githubusercontent.com/69501902/104260475-924d7000-54be-11eb-8108-b096105a80e3.png)
