### ISSUE TITLE
Using LIMIT with or without pipe returns the same result

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#586]
nGQL 1: MATCH (v:player{name:"Tim Duncan"}) --> (v2) RETURN v2 | LIMIT 3
nGQL 2: MATCH (v:player{name:"Tim Duncan"}) --> (v2) RETURN v2 LIMIT 3

![image](https://user-images.githubusercontent.com/69501902/104178863-f5e78700-5445-11eb-9369-e5ebd1ff952b.png)

Is it coded to be like this?

**Comment by CPWstatic** [comment]
These two statement are both legal in nGQL. The first one was derived from nebula1.0 and the second one is an openCypher syntax.
