### ISSUE TITLE
Inconsistent behavior related to LIMIT and pipe

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#588]
As mentioned in [this issue](https://github.com/vesoft-inc/nebula-graph/issues/586), using LIMIT with or without pipe returns the same result, then why not here:

![image](https://user-images.githubusercontent.com/69501902/104179775-59be7f80-5447-11eb-83f3-f05dd0cc235f.png)

**Comment by CPWstatic** [comment]
The first one should be:
```
Match ... | Order ... | Limit ...
```
