### ISSUE TITLE
2.0 alter tag fails

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-graph#592]
I have a tag named `testme`. See the following picture 
![image](https://user-imagI es.githubusercontent.com/42762957/104263021-b52e5300-54c3-11eb-8d5e-d7c915be6f54.png)
![image](https://user-images.githubusercontent.com/42762957/104264846-59fe5f80-54c7-11eb-92df-37bdf014037a.png)

I can’t alter this tag. Failed when trying to add a new property.
![image](https://user-images.githubusercontent.com/42762957/104263163-00486600-54c4-11eb-9aab-a9af3bbcaf7d.png)
Succeed in dropping a property 

![image](https://user-images.githubusercontent.com/42762957/104264789-3e935480-54c7-11eb-9869-4ab8a75f705e.png)

Totally confused. After dropping a property, I can add new properties. So strange

**Comment by laura-ding** [comment]
alter add failed, it tells you syntax error, you need to delete the `,` between `(p4, string)`

**Comment by laura-ding** [comment]
No more questions. I close it now.
