### ISSUE TITLE
match : indexScan not push down

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula-graph#598]
<img width="1221" alt="00EB8CD6-C9A2-4252-8448-02A39E055101" src="https://user-images.githubusercontent.com/6930445/104293674-3bb15780-54f9-11eb-9b13-2fce94bc2d5b.png">
test case:
match (n:team{name:"Spurs"})-[]->() return n

**Comment by yixinglu** [comment]
have been fixed in #619
