### ISSUE TITLE
go:  Inconsistent results

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula-graph#601]
![A80ABB56-1F48-4DBE-848C-36CF56898CFF](https://user-images.githubusercontent.com/6930445/104299572-5c30e000-5500-11eb-9274-188f153b4e3a.png)

**Comment by tom-chensf** [comment]
(root@nebula) [test1]> go from "1" over edge1 yield edge1._dst,1
+------------+---+
| edge1._dst | 1 |
+------------+---+
| "2"        | 1 |
+------------+---+
Got 1 rows (time spent 2652/3384 us)

Your query serve._dst is empty ，so there is no output.

**Comment by HarrisChu** [comment]
fixed in v2.0.1, close it
