### ISSUE TITLE
[openCypher compatibility] Can't use ASCENDING after ORDER BY

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#603]
nGQL: MATCH (v:player) RETURN v.age AS Age, v.name AS Name, id(v) as ID | ORDER BY ID ASCENDING | LIMIT 5

![image](https://user-images.githubusercontent.com/69501902/104404820-8a60ff00-5596-11eb-832c-6c54db766b69.png)

openCypher:
![image](https://user-images.githubusercontent.com/69501902/104404698-3fdf8280-5596-11eb-99c9-ab6a18c171a7.png)

**Comment by czpmango** [comment]
`MATCH (v:player) RETURN v.age AS Age, v.name AS Name, id(v) as ID | ORDER BY ID ASC | LIMIT 5`

**Comment by randomJoe211** [comment]
> `MATCH (v:player) RETURN v.age AS Age, v.name AS Name, id(v) as ID | ORDER BY ID ASC | LIMIT 5`

This is a compatibility problem. OpenCypher supports ASCENDING and DESCENDING, but nGQL for now don't.

**Comment by czpmango** [comment]
> > `MATCH (v:player) RETURN v.age AS Age, v.name AS Name, id(v) as ID | ORDER BY ID ASC | LIMIT 5`
> 
> This is a compatibility problem. OpenCypher supports ASCENDING and DESCENDING, but nGQL for now don't.

ACK.
