### ISSUE TITLE
Problem with offset in LIMIT in MATCH

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#610]
I can use `LIMIT` without a pipe in `MATCH`, but I can't set an offset in a `LIMIT` clause without a pipe in `MATCH`. Why?
nGQL: MATCH (v:player) RETURN v.name AS Name ORDER BY Name LIMIT 3, 5

![image](https://user-images.githubusercontent.com/69501902/104559332-31b96100-567f-11eb-9463-22c75ea83b6b.png)

![image](https://user-images.githubusercontent.com/69501902/104559361-3da52300-567f-11eb-873b-5d509f876fb7.png)

**Comment by czpmango** [comment]
The statement in the second image is actually a mix of nGql and Cypher syntax.
Currently the syntax of Match is the same as that of Cypher and does not support syntax like limit 3,5.

**Comment by whitewum** [comment]
> Currently the syntax of Match is the same as that of Cypher and does not support syntax like limit 3,5.

Agree.
