### ISSUE TITLE
SKIP cannot work with GO, LOOKUP, etc.

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#617]
As the title states.

![image](https://user-images.githubusercontent.com/69501902/104583111-b6b27380-569b-11eb-93ee-22984a91cf29.png)

Looks like it only works with MATCH.

**Comment by czpmango** [comment]
`GO FROM "player100" OVER follow | OFFSET 1 LIMIT 2`
 nGql and cypher have different syntax.

**Comment by whitewum** [comment]
> `GO FROM "player100" OVER follow | OFFSET 1 LIMIT 2`
> nGql and cypher have different syntax.

agreed
