### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula-graph#621]
➜  nebula-console git:(master) ./nebula-console -u u -p p --address 127.0.0.1 --port 9669
2021/01/15 14:15:48 [INFO] connection pool is initialized successfully

Welcome to Nebula Graph v2.0.0-rc1!

(u@nebula) [(none)]> YIELD -9223372036854775807
+------------------------+
| -(9223372036854775807) |
+------------------------+
| -9223372036854775807   |
+------------------------+
Got 1 rows (time spent 567/4549 us)

Fri, 15 Jan 2021 14:15:51 CST

(u@nebula) [(none)]> YIELD -9223372036854775808
+-------------------------+
| -(-9223372036854775808) |
+-------------------------+
| -9223372036854775808    |
+-------------------------+
Got 1 rows (time spent 538/5978 us)

Fri, 15 Jan 2021 14:15:55 CST

https://godbolt.org/z/ds13KE

**Comment by CPWstatic** [comment]
#538 we had a same issue.

**Comment by Aiee** [comment]
Working on it right now.
