### ISSUE TITLE
[openCypher tck case]  invalid integer error check 

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula-graph#654]
```

(czp@nebula) [nba]> yield 9223372#54775808 AS literal
+---------+
| 9223372 |
+---------+
| 9223372 |
+---------+
Got 1 rows (time spent 19652/29050 us)

```

**Comment by laura-ding** [comment]
`#54775808 AS literal` it's the comment, not a bug.

**Comment by czpmango** [comment]
You are right! 
But, this is a tck test case of openCypher. (Will we consider keeping it consistent with openCypher？
```
  @NegativeTest
  Scenario: [12] Fail on an integer containing a invalid symbol character
    Given any graph
    When executing query:
      """
      RETURN 9223372#54775808 AS literal
      """
    Then a SyntaxError should be raised at compile time: InvalidNumberLiteral
```

**Comment by whitewum** [comment]
> You are right!
> But, this is a tck test case of openCypher. (Will we consider keeping it consistent with openCypher？
> 
> ```
>   @NegativeTest
>   Scenario: [12] Fail on an integer containing a invalid symbol character
>     Given any graph
>     When executing query:
>       """
>       RETURN 9223372#54775808 AS literal
>       """
>     Then a SyntaxError should be raised at compile time: InvalidNumberLiteral
> ```

If this comment `#`  will not compatible by design, I'll write in doc.
