### ISSUE TITLE
Different sorting method in two same semantics queries

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-graph#659]
As title. I write two different queries to return the same thing. But the sorting method is different. Why is this?
![image](https://user-images.githubusercontent.com/42762957/105153838-dc2ff900-5b43-11eb-8a0d-157a892c3b96.png)
![image](https://user-images.githubusercontent.com/42762957/105153853-e225da00-5b43-11eb-8e02-30cdf5138d68.png)
**Besides, sometimes when I run the same query several times, the sorting method is different, too.**

**Comment by czpmango** [comment]
There are many factors that can lead to inconsistent order of query results, that's just alright.
You can use `order by` clause to ensure the order of query results.

**Comment by Amber1990Zhang** [comment]
Thanks for your kind reply. Then what about 

> Besides, sometimes when I run the same query several times, the sorting method is different, too.

**Comment by czpmango** [comment]
> Thanks for your kind reply. Then what about
> 
> > Besides, sometimes when I run the same query several times, the sorting method is different, too.

Could you describe your test scenario in detail?

**Comment by czpmango** [comment]
IMO,this is not a concern. 
Bcz, the order of the query results is very likely to be inconsistent in distributed scenarios and there is absolutely no query language standard that requires consistency in the order of query results.

**Comment by whitewum** [comment]
add an order-by clause.
