### ISSUE TITLE
[openCypher Compatibility] Why must WITH used with an alias?

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#663]
![image](https://user-images.githubusercontent.com/69501902/105311211-57eb7d80-5bf8-11eb-8bbb-2b90d1018d3b.png)

openCypher needs no alias while using WITH:

![image](https://user-images.githubusercontent.com/69501902/105311544-6afe4d80-5bf8-11eb-97bd-003ebe401570.png)

**Comment by czpmango** [comment]
The with clause items require alias, whereas Neo4j just provides the default alias.
This is my test:
```
neo4j@neo4j> match (n) with n,1+1 return n;
Expression in WITH must be aliased (use AS) (line 2, column 17 (offset: 17))
"match (n) with n,1+1 return n;"
                 ^
```

**Comment by czpmango** [comment]
Same as this issue: [https://github.com/vesoft-inc/nebula-graph/issues/624](https://github.com/vesoft-inc/nebula-graph/issues/624)

**Comment by randomJoe211** [comment]
Can we have a default alias as well?

**Comment by czpmango** [comment]
> Can we have a default alias as well?

Feature.

**Comment by randomJoe211** [comment]
It's also a compatibility problem that makes the use of openCypher syntax in nGQL troublesome.

**Comment by czpmango** [comment]
> It's also a compatibility problem that makes the use of openCypher syntax in nGQL troublesome.

ACK.
