### ISSUE TITLE
[openCypher Compatibility] Fail to order by the parameter that WITH carries

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#666]
Failed nGQL: MATCH (v:player) WITH v as v ORDER BY v.name DESC LIMIT 3 RETURN v.name

![image](https://user-images.githubusercontent.com/69501902/105315958-20ca9b80-5bfb-11eb-8168-dd821c3d64c0.png)

Related openCypher example:

![image](https://user-images.githubusercontent.com/69501902/105316978-997e2780-5bfc-11eb-9f3b-8a5261213e83.png)

**Comment by czpmango** [comment]
Same as this issue: [https://github.com/vesoft-inc/nebula-graph/issues/613](https://github.com/vesoft-inc/nebula-graph/issues/613)

**Comment by whitewum** [comment]
I met this problem again...
