### ISSUE TITLE
using count() in WITH causes a crash

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#668]
![image](https://user-images.githubusercontent.com/69501902/105340727-3e0e6280-5c19-11eb-8a52-d9be9635b3d3.png)

**Comment by czpmango** [comment]
Not supported yet. Same as [https://github.com/vesoft-inc/nebula-graph/issues/648](https://github.com/vesoft-inc/nebula-graph/issues/648).
