### ISSUE TITLE
[openCypher Compatibility] Support for parameters

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#675]
I can't create nodes from a list parameter because nGQL does not support parameters yet.

![image](https://user-images.githubusercontent.com/69501902/105456777-b67c2e80-5cc0-11eb-852c-4011440ecf08.png)

**Comment by czpmango** [comment]
This is the format of openCypher's tck test case.
It is recommended to execute the statement in the neo4j console to ensure the accuracy of the description.

**Comment by czpmango** [comment]
:param events=>[{ year : 2014, id : 1},{ year : 2014, id : 2}];
unwind $events as event
merge (y:Year {year:event.year})
merge (y)<-[:IN]-(e:Event {id:event.id})
return e.id as x
order by x;

**Comment by czpmango** [comment]
This is my test in neo4j console:
```
neo4j@neo4j> :param events=>[{ year : 2014, id : 1},{ year : 2014, id : 2}];
neo4j@neo4j> unwind $events as event
             merge (y:Year {year:event.year})
             merge (y)<-[:IN]-(e:Event {id:event.id})
             return e.id as x
             order by x;
+---+
| x |
+---+
| 1 |
| 2 |
+---+

2 rows available after 1376 ms, consumed after another 830 ms
Added 3 nodes, Created 2 relationships, Set 3 properties, Added 3 labels
```

**Comment by czpmango** [comment]
@randomJoe211 
You could use the markdown format to describe the issue instead of the picture. Because the picture is not convenient to copy.

**Comment by randomJoe211** [comment]
> @randomJoe211
> You could use the markdown format to describe the issue instead of the picture. Because the picture is not convenient to copy.

Sure. I'll do that. Thanks.

**Comment by CPWstatic** [comment]
Please keep track with https://github.com/vesoft-inc/nebula/issues/2593
