### ISSUE TITLE
关于边自动生成rank的一个想法

### ISSUE THREAD

**Issue by ConleyKong** [vesoft-inc/nebula-graph#687]
目前的nebula的rank是需要用户自己指定的，要么使用自定义的int型要么使用时间戳，但是这种使用方式都不是很方便，有种想法不知道可行不可行，就是在插入边时自动生成rank，生成rank的规则就是边上的属性基于固定规则组成字符串后的hash结果，由于nebula内部的哈希返回的就是一个整数，因此就可以实现了自动的边区分

**Comment by jude-zhu** [comment]
可以业务自己去做，(#^.^#)
