### ISSUE TITLE
Does string supports `regexp` match?

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-graph#690]
![image](https://user-images.githubusercontent.com/42762957/105792686-c34f9980-5fc2-11eb-8eb6-04aabed3f535.png)
I think nebula supports `regexp` for some time. But now it doesn't anymore.

![image](https://user-images.githubusercontent.com/42762957/105792627-b337ba00-5fc2-11eb-8b1a-cb37d7179353.png)

**Comment by randomJoe211** [comment]
I'm having the same question.

**Comment by jievince** [comment]
It's not `regex`'s problem. Fetch prop on doesn't support `where` clause.
