### ISSUE TITLE
[openCypher compatibility] Fail to use square bracket syntax

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#694]
nGQL: MATCH (v:player) WHERE v[toLower("AGE")] < 30 RETURN v.name, v.age;

![image](https://user-images.githubusercontent.com/69501902/105986389-d43dff00-60d7-11eb-853c-2bc478797060.png)

Not sure why it returned `Empty set`.

OpenCypher supports this syntax:
WITH 'AGE' AS propname
MATCH (n)
WHERE n[toLower(propname)]< 30
RETURN n.name, n.age
![image](https://user-images.githubusercontent.com/69501902/105986441-ea4bbf80-60d7-11eb-95b0-50743f3f1626.png)

**Comment by jievince** [comment]
Fixed it in https://github.com/vesoft-inc/nebula-common/pull/399

**Comment by randomJoe211** [comment]
> Fixed it in [vesoft-inc/nebula-common#399](https://github.com/vesoft-inc/nebula-common/pull/399)

Awesome!
