### ISSUE TITLE
[openCypher compatibility] Fail to do property existence checking with WHERE

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#695]
openCypher supports property existence checking:
![image](https://user-images.githubusercontent.com/69501902/106087916-ecf1f780-615f-11eb-8694-82feb99efe42.png)

nGQL does not support the exists() function. So the following statements failed.
MATCH (v) WHERE exists(v.age) RETURN v.name, v.age;
MATCH (v:player) WHERE exists(v.age) RETURN v.name, v.age;
![image](https://user-images.githubusercontent.com/69501902/106087966-01ce8b00-6160-11eb-9dd8-e3bbf29c863c.png)

**Comment by randomJoe211** [comment]
Besides, I'm not sure if `MATCH (v) WHERE exists(v.age) RETURN v.name, v.age;` works even nGQL supports exists(). Because MATCH in nGQL needs an index but can it use the age index with this statement? Theoretically, it should be able to.

**Comment by czpmango** [comment]
Similar with [https://github.com/vesoft-inc/nebula-graph/issues/673](https://github.com/vesoft-inc/nebula-graph/issues/673)

**Comment by nevermore3** [comment]
https://github.com/vesoft-inc/nebula-graph/pull/808
