### ISSUE TITLE
[open cypher tck incompatible] Scenario: Return a single-quoted string 

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#696]
```
  file: Literals.feature

  Scenario: Return a single-quoted string
    When executing query:
      """
      RETURN '' AS literal
      """
    Then the result should be, in any order:
      | literal |
      | ''      |    --it should be single-quoted
    And no side effects
```

`YIELD` has minor return problem.

 
![image](https://user-images.githubusercontent.com/50101159/106093925-26306480-616c-11eb-8e2e-5ab71f298de7.png)

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/106094107-74ddfe80-616c-11eb-9078-0380aa2e10ee.png)

is it proper to change single-quote to double-quote?

**Comment by czpmango** [comment]
That’s alright.

**Comment by whitewum** [comment]
> That’s alright.

I agree it is a minor inconsistency.  But I think we should be clear with the community what's the difference.

**Comment by czpmango** [comment]
```
neo4j@neo4j> return ' ' as a;
+-----+
| a   |
+-----+
| " " |
+-----+
```

**Comment by whitewum** [comment]
But, That indicates neo4j is not fully openCypher compatible.
The bahavior is against the TCK.
