### ISSUE TITLE
[opencypher tck incompatible] max() can't work on strings

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#699]
```
file AggregationAcceptance.feature

  Scenario: `max()` should aggregate strings
    Given any graph
    When executing query:
      """
      UNWIND ['a', 'b', 'B', null, 'abc', 'abc1'] AS i
      RETURN max(i)
      """
    Then the result should be, in any order:
      | max(i) |
      | 'b'    |
    And no side effects
```

![image](https://user-images.githubusercontent.com/50101159/106096153-f4210180-616f-11eb-8e23-4b58ee3cb1ed.png)

**Comment by czpmango** [comment]
Similar with [https://github.com/vesoft-inc/nebula-graph/issues/678](https://github.com/vesoft-inc/nebula-graph/issues/678)

**Comment by czpmango** [comment]
Fixed in [https://github.com/vesoft-inc/nebula-graph/pull/681](https://github.com/vesoft-inc/nebula-graph/pull/681)

**Comment by czpmango** [comment]
Already fixed. Plz retest and close this issue. @whitewum

**Comment by czpmango** [comment]
Already fixed. @whitewum
