### ISSUE TITLE
[opencypher incompatible] LIST comprehension don't work

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#703]
![image](https://user-images.githubusercontent.com/50101159/106099384-8bd51e80-6175-11eb-8393-1919104960c0.png)

replace `RETURN` with `YIELD`. but none of the above `Query` examples can run.

![image](https://user-images.githubusercontent.com/50101159/106099491-b9ba6300-6175-11eb-9e3b-43730589ef1e.png)

**Comment by czpmango** [comment]
This is my test:
```
(czp@nebula) [nba]> yield [x in range(0,10) where x%2==0| x+1] as result
+---------------------+
| result              |
+---------------------+
| [1, 3, 5, 7, 9, 11] |
+---------------------+
(czp@nebula) [nba]> yield x^3
[ERROR (-7)]: SyntaxError: syntax error near `^3'

```

**Comment by jievince** [comment]
It's not a problem with list comprehension.
1. we don't support `^` any more;
2. we do not support the use of an `=` to indicate `==`

**Comment by whitewum** [comment]
> It's not a problem with list comprehension.
> 
> 1. we don't support `^` any more;
> 2. we do not support the use of an `=` to indicate `==`

OK. Now `^` is incompatible.
