### ISSUE TITLE
range() compatible problems

### ISSUE THREAD

**Issue by Amber1990Zhang** [vesoft-inc/nebula-graph#705]
![image](https://user-images.githubusercontent.com/42762957/106101377-c68c8600-6178-11eb-8991-a149aacd185d.png)

**Comment by Amber1990Zhang** [comment]
![image](https://user-images.githubusercontent.com/42762957/106101619-19fed400-6179-11eb-9060-22ade6454957.png)
https://neo4j.com/docs/cypher-manual/current/syntax/lists/#cypher-list-comprehension

**Comment by czpmango** [comment]
This has nothing to do with range function. 
Similar with [https://github.com/vesoft-inc/nebula-graph/issues/645](https://github.com/vesoft-inc/nebula-graph/issues/645)

**Comment by yixinglu** [comment]
fixed in #991
