### ISSUE TITLE
[opencypher incompatible] type convertion functions are not implemented

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#706]
![image](https://user-images.githubusercontent.com/50101159/106102947-1ff5b480-617b-11eb-8f65-5e0353a303ac.png)
The opencypher requires 4 type conversion functions. 
But they are not implemented.

![image](https://user-images.githubusercontent.com/50101159/106103051-49aedb80-617b-11eb-9f51-ce0dd8f339e0.png)

**Comment by czpmango** [comment]
Function `type` is correct.
This is my test:
```
(czp@nebula) [nba]> match (a:player)-[e]-() return type(e)
+------------+
| type(e)    |
+------------+
| "like"     |
+------------+
| "like"     |
+------------+

```

**Comment by czpmango** [comment]
```
(czp@nebula) [nba]> yield (bool)(3);
+---------+
| (BOOL)3 |
+---------+
| true    |
+---------+

```

**Comment by czpmango** [comment]
[https://github.com/vesoft-inc/nebula-graph/issues/677](https://github.com/vesoft-inc/nebula-graph/issues/677)

**Comment by whitewum** [comment]
> Function `type` is correct.
> This is my test:
> 
> ```
> (czp@nebula) [nba]> match (a:player)-[e]-() return type(e)
> +------------+
> | type(e)    |
> +------------+
> | "like"     |
> +------------+
> | "like"     |
> +------------+
> ```

Agreed.
type(e) only works for edges. It doesn't work for anything else.

BUT, please also notice the error message. (minor difference)

```
TCK

  Scenario: Failing when using `type()` on a node
    When executing query:
      """
      MATCH (r)
      RETURN type(r)
      """
    Then a SyntaxError should be raised at compile time: InvalidArgumentType -- the error message
```

**Comment by czpmango** [comment]
ACK.

**Comment by whitewum** [comment]
> ```
> (czp@nebula) [nba]> yield (bool)(3);
> +---------+
> | (BOOL)3 |
> +---------+
> | true    |
> +---------+
> ```

#813

please notice that the behavior changed from Jan. WHY.

**Comment by czpmango** [comment]
> > ```
> > (czp@nebula) [nba]> yield (bool)(3);
> > +---------+
> > | (BOOL)3 |
> > +---------+
> > | true    |
> > +---------+
> > ```
> 
> #813
> 
> please notice that the behavior changed from Jan. WHY.

It is illegal to convert an integer to a boolean.

**Comment by whitewum** [comment]
> > > ```
> > > (czp@nebula) [nba]> yield (bool)(3);
> > > +---------+
> > > | (BOOL)3 |
> > > +---------+
> > > | true    |
> > > +---------+
> > > ```
> > 
> > 
> > #813
> > please notice that the behavior changed from Jan. WHY.
> 
> It is illegal to convert an integer to a boolean.

if so, it is a behavior-changing design.
