### ISSUE TITLE
client crashed with a query

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#707]
![image](https://user-images.githubusercontent.com/50101159/106106430-7c0f0780-6180-11eb-82e8-4b6232efc0cb.png)

```
with collect_set([1,2,3]) as a unwind a as b return b
```

My aim is to test whether collect returns a {} or a [] ?

**Comment by czpmango** [comment]
Same as [https://github.com/vesoft-inc/nebula-graph/issues/648](https://github.com/vesoft-inc/nebula-graph/issues/648)
