### ISSUE TITLE
RETRUN-ORDERBY-collect sequence bug

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#725]
![image](https://user-images.githubusercontent.com/50101159/106434801-fc997500-64ac-11eb-8f3c-fc51ae4c6c69.png)

```
MATCH (v:player)         WITH v.name AS Name  RETURN collect(Name)   ORDER BY Name DESC         LIMIT 3         ;
[ERROR (-12)]: SemanticError: Column `Name' not found
```

This sentence is legal. Why SemanticError? 

And why other sequences are legal.

**Comment by jievince** [comment]
It's illegal in cypher too.
We can only `ORDER BY` the variables which are `RETURN`ed.
Because you `RETURN` `collect(Name)`, so you only `ORDER BY` `collect(Name)`.

**Comment by jievince** [comment]
`RETURN collect(Name)` builds a table which has one column called `collect(Name)`. And then pass the table to `ORDER BY` clause to sort it. The `ORDER BY` sorts the table by column name, and there is no column called `Name` in the table.
![image](https://user-images.githubusercontent.com/38901892/106838738-ce4bad80-66d7-11eb-816d-87d937128e37.png)

**Comment by czpmango** [comment]
```
neo4j@neo4j> MATCH (v:player) WITH v.name AS Name  RETURN collect(Name) ORDER BY Name DESC LIMIT 3;
In a WITH/RETURN with DISTINCT or an aggregation, it is not possible to access variables declared before the WITH/RETURN: Name (line 2, column 69 (offset: 69))
"MATCH (v:player) WITH v.name AS Name  RETURN collect(Name) ORDER BY Name DESC LIMIT 3;"
```
