### ISSUE TITLE
Odd output of FETCH

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#750]
When I try to use FETCH to query a source/destination vertex ID of an edge, or its rank value, the output is odd. They not only contain the field I queried, but also contain some fields that I never ask for.

![image](https://user-images.githubusercontent.com/69501902/108313568-7f336b80-71f3-11eb-9716-79854f08fd8d.png)

nGQL: FETCH PROP ON serve "player100" -> "team204" YIELD serve._dst;

Please consider optimizing this behavior.

**Comment by HarrisChu** [comment]
By Design, close it
