### ISSUE TITLE
When creating a space, does vid_type not have a default value?

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula-graph#754]
> create space lzy (partition_num=10)
> use lzy
> create tag player(name string,age int)
> INSERT VERTEX player(name,age) VALUES "player001":("lzy11",18)
[ERROR (-8)]: Storage Error: The VID must be a 64-bit interger or a string.

**Comment by laura-ding** [comment]
The default value of vid_type is  fixed_string(8), which means the length of the vid can’t large than 8, the length of vid “player001” is 9.  so it tells you the vid is wrong.
