### ISSUE TITLE
update/upsert when statement improves

### ISSUE THREAD

**Issue by panda-sheep** [vesoft-inc/nebula-graph#762]
```
create space y2(partition_num=1, replica_factor=1, vid_type=int64);
use y2
create tag tag2(col1 int,col2 bool,col3 string);
insert vertex tag2(col1,col2,col3) values 1:(1,true,"aaa");

(user@nebula) [y2]> fetch prop on tag2 1
+----------+-----------+-----------+-----------+
| VertexID | tag2.col1 | tag2.col2 | tag2.col3 |
+----------+-----------+-----------+-----------+
| 1        | 1         | true      | "aaa"     |
+----------+-----------+-----------+-----------+
Got 1 rows (time spent 3783/4221 us)

update vertex on tag2 1 set col3="bbb" when col1;  
```

`update vertex on tag2 1 set col3="bbb" when col1;`
This statement should report a syntax error

**Comment by laura-ding** [comment]
> ```
> create space y2(partition_num=1, replica_factor=1, vid_type=int64);
> use y2
> create tag tag2(col1 int,col2 bool,col3 string);
> insert vertex tag2(col1,col2,col3) values 1:(1,true,"aaa");
> 
> (user@nebula) [y2]> fetch prop on tag2 1
> +----------+-----------+-----------+-----------+
> | VertexID | tag2.col1 | tag2.col2 | tag2.col3 |
> +----------+-----------+-----------+-----------+
> | 1        | 1         | true      | "aaa"     |
> +----------+-----------+-----------+-----------+
> Got 1 rows (time spent 3783/4221 us)
> 
> update vertex on tag2 1 set col3="bbb" when col1;  
> ```
> 
> `update vertex on tag2 1 set col3="bbb" when col1;`
> This statement should report a syntax error

why? `when col1` is right expression.

**Comment by panda-sheep** [comment]
https://github.com/vesoft-inc/nebula-common/pull/412 
This pr requires `when/where` must be followed by：
1) bool expression
2) Bool type column
3) String type column

**Comment by czpmango** [comment]
> [vesoft-inc/nebula-common#412](https://github.com/vesoft-inc/nebula-common/pull/412)
> This pr requires `when/where` must be followed by：
> 
> 1. bool expression
> 2. Bool type column
> 3. String type column

This issue has nothing to do with pr 412. Should follow update/upsert’s own implementation logic, and I don’t think the implementation of update/upsert needs to call type casting.

**Comment by czpmango** [comment]
> > ```
> > create space y2(partition_num=1, replica_factor=1, vid_type=int64);
> > use y2
> > create tag tag2(col1 int,col2 bool,col3 string);
> > insert vertex tag2(col1,col2,col3) values 1:(1,true,"aaa");
> > 
> > (user@nebula) [y2]> fetch prop on tag2 1
> > +----------+-----------+-----------+-----------+
> > | VertexID | tag2.col1 | tag2.col2 | tag2.col3 |
> > +----------+-----------+-----------+-----------+
> > | 1        | 1         | true      | "aaa"     |
> > +----------+-----------+-----------+-----------+
> > Got 1 rows (time spent 3783/4221 us)
> > 
> > update vertex on tag2 1 set col3="bbb" when col1;  
> > ```
> > 
> > 
> > `update vertex on tag2 1 set col3="bbb" when col1;`
> > This statement should report a syntax error
> 
> why? `when col1` is right expression.

IMO, `when col2` is correct, but `when col1` should report a semantic error.

**Comment by panda-sheep** [comment]
> .
If the graph does not handle it, then the pr` https://github.com/vesoft-inc/nebula-storage/pull/352`   is incorrect

**Comment by czpmango** [comment]
nebula test:
```
(czp@nebula) [test]> match (v:t1) return v;
+------------------------------------------------------+
| v                                                    |
+------------------------------------------------------+
| (1 :t1{a: 43, b: true} :person{age: 2, name: "Tom"}) |
+------------------------------------------------------+
Got 1 rows (time spent 265698/274002 us)

(czp@nebula) [test]>  upsert vertex on t1 1 set a = "x" when "xyz"
[ERROR (-8)]: Storage Error: Invalid data, may be wrong value type.

(czp@nebula) [test]>  upsert vertex on t1 1 set a = 4.1 when "xyz"
Execution succeeded (time spent 55584/64959 us)

(czp@nebula) [test]> match (v:t1) return v;
+-----------------------------------------------------+
| v                                                   |
+-----------------------------------------------------+
| (1 :t1{a: 4, b: true} :person{age: 2, name: "Tom"}) |
+-----------------------------------------------------+
Got 1 rows (time spent 262812/273576 us)
```

neo4j test:
```
neo4j@neo4j> create (n:t1{a:1,b:true});
0 rows available after 5 ms, consumed after another 0 ms
Added 1 nodes, Set 2 properties, Added 1 labels
neo4j@neo4j>  match (n:t1)  return n;
+-----------------------+
| n                     |
+-----------------------+
| (:t1 {a: 1, b: TRUE}) |
+-----------------------+

1 row available after 3 ms, consumed after another 2 ms
neo4j@neo4j>  match (n:t1) where n.b set n.a=3 return n;
+-----------------------+
| n                     |
+-----------------------+
| (:t1 {a: 3, b: TRUE}) |
+-----------------------+

1 row available after 3 ms, consumed after another 2 ms
Set 1 properties
neo4j@neo4j>  match (n:t1)  return n;
+-----------------------+
| n                     |
+-----------------------+
| (:t1 {a: 3, b: TRUE}) |
+-----------------------+

1 row available after 2 ms, consumed after another 1 ms
neo4j@neo4j>  match (n:t1) where n.a set n.a=3 return n;
Don't know how to treat that as a predicate: Long(3)
neo4j@neo4j>  match (n:t1) where "xyz" set n.a=3 return n;
Type mismatch: expected Boolean but was String (line 2, column 20 (offset: 21))
" match (n:t1) where "xyz" set n.a=3 return n;"
```
