### ISSUE TITLE
IF NOT EXISTS clause is invalid

### ISSUE THREAD

**Issue by cooper-lzy** [vesoft-inc/nebula-graph#774]
If the IF NOT EXISTS clause is given, the statement produces a warning for each named user that already exists, rather than an error.

(root@nebula) [(none)]> create user lzy with password '123'
[ERROR (-8)]: Existed!

(root@nebula) [(none)]> create user if not exists lzy with password '123'
Execution succeeded (time spent 1065/1609 us)

(root@nebula) [(none)]> create user if not exists lzy with password '123'
Execution succeeded (time spent 830/1324 us)

**Comment by Aiee** [comment]
According to the doc: https://docs.nebula-graph.io/1.1/manual-EN/3.build-develop-and-administration/4.account-management-statements/create-user-syntax/

> By default, an error occurs if you try to create a user that already exists. If the IF NOT EXISTS clause is given, the statement produces a warning for each named user that already exists, rather than an error.
