### ISSUE TITLE
match clause with function id throw error and exit

### ISSUE THREAD

**Issue by zcw5116** [vesoft-inc/nebula-graph#778]
version: v2.0.0-alpha
when executing the following clause, throw an error and exit the nebula-console.

(user@nebula) [nba]> MATCH (a:player)-[r]->() where id(a)=="player100"  RETURN labels(a),  keys(r), id(a);
2021/03/02 17:52:13 [ERROR] Failed to reconnect, Failed to open transport, error: dial tcp 192.168.118.200:9669: connect: connection refused
2021/03/02 17:52:13 Loop error, Failed to open transport, error: dial tcp 192.168.118.200:9669: connect: connection refused

Bye user!
Tue, 02 Mar 2021 17:52:13 CST

panic: Loop error, Failed to open transport, error: dial tcp 192.168.118.200:9669: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x78e4fb, 0xe, 0xc0000e7e98, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.14.13/x64/src/log/log.go:358 +0xc0
main.main()
	/home/runner/work/nebula-console/nebula-console/main.go:366 +0x49e

**Comment by Aiee** [comment]
Hello, as I test with the demo NBA dataset, I am able to execute the query and get a valid result. I am using the nightly version. I'd like to suggest you use the rc1 and see if this error persists. Also, check the version of Nebula console and make sure the console is compatible with the Nebula service.

![Screen Shot 2021-03-02 at 6 00 02 PM](https://user-images.githubusercontent.com/18348405/109631641-1ea41700-7b81-11eb-8bb7-b1353145803e.png)

**Comment by zcw5116** [comment]
> Hello, as I test with the demo NBA dataset, I am able to execute the query and get a valid result. I am using the nightly version. I'd like to suggest you use the rc1 and see if this error persists. Also, check the version of Nebula console and make sure the console is compatible with the Nebula service.
> 
> ![Screen Shot 2021-03-02 at 6 00 02 PM](https://user-images.githubusercontent.com/18348405/109631641-1ea41700-7b81-11eb-8bb7-b1353145803e.png)



I was using docker compose according document from nebula offitial website. 
1. Operation steps 
step1:  start a new docker container with the Nebula Console image
$ docker run --rm -ti --network nebula-docker-compose_nebula-net --entrypoint=/bin/sh vesoft/nebula-console:v2-nightly

step2: Connect to Nebula Graph with Nebula Console.
nebula-console -u user -p password --address=graphd --port=9669


2. Nebula version info
/ # nebula-console -u user -p password --address=graphd --port=9669
Welcome to Nebula Graph v2.0.0-rc1!


 docker compose problem ？
thank you very much

**Comment by Aiee** [comment]
> > Hello, as I test with the demo NBA dataset, I am able to execute the query and get a valid result. I am using the nightly version. I'd like to suggest you use the rc1 and see if this error persists. Also, check the version of Nebula console and make sure the console is compatible with the Nebula service.
> > ![Screen Shot 2021-03-02 at 6 00 02 PM](https://user-images.githubusercontent.com/18348405/109631641-1ea41700-7b81-11eb-8bb7-b1353145803e.png)
> 
> I was using docker compose according document from nebula offitial website.
> 
> 1. Operation steps
>    step1:  start a new docker container with the Nebula Console image
>    $ docker run --rm -ti --network nebula-docker-compose_nebula-net --entrypoint=/bin/sh vesoft/nebula-console:v2-nightly
> 
> step2: Connect to Nebula Graph with Nebula Console.
> nebula-console -u user -p password --address=graphd --port=9669
> 
> 1. Nebula version info
>    / # nebula-console -u user -p password --address=graphd --port=9669
>    Welcome to Nebula Graph v2.0.0-rc1!
> 
> docker compose problem ？
> thank you very much

Hi, does the problem persist? If you need further support with Nebula Graph, please post your question on the forum: 
https://discuss.nebula-graph.io/ (English)
https://discuss.nebula-graph.com.cn/ (Chinese)

The on-call team is always there to help.

**Comment by yixinglu** [comment]
we have released nebula 2.0.1, please try to test your query in new nebula version. now i close this issue, if there still exists some problems, append more information here.  thx.
