### ISSUE TITLE
Function `collect' not defined

### ISSUE THREAD

**Issue by zcw5116** [vesoft-inc/nebula-graph#786]
version： Nebula Graph v2.0.0-rc1!

(user@nebula) [nba]> UNWIND [1, 2, 1] AS a RETURN collect(a);
[ERROR (-12)]: SemanticError: `collect(a)' is not a valid expression : Function `collect' not defined

document：https://docs.nebula-graph.io/2.0/3.ngql-guide/6.functions-and-expressions/10.collect/

**Comment by Aiee** [comment]
Hello,
I am able to execute the query without a problem. Please notice the welcome message you see after connect using console doesn't represent the version of Nebula service. That's the version of your console. I'd recommend you to check your service version and make sure it is up to date.

![Screen Shot 2021-03-05 at 12 02 02 PM](https://user-images.githubusercontent.com/18348405/110065639-9a34dc80-7daa-11eb-930d-d28cacc3ff17.png)

**Comment by zcw5116** [comment]
OK, Thank You.
BTW, how to query Service Version?

**Comment by zcw5116** [comment]
> Hello,
> I am able to execute the query without a problem. Please notice the welcome message you see after connect using console doesn't represent the version of Nebula service. That's the version of your console. I'd recommend you to check your service version and make sure it is up to date.
> 
> ![Screen Shot 2021-03-05 at 12 02 02 PM](https://user-images.githubusercontent.com/18348405/110065639-9a34dc80-7daa-11eb-930d-d28cacc3ff17.png)

OK, Thank You.
BTW, how to query Service Version?

**Comment by zcw5116** [comment]
> Hello,
> I am able to execute the query without a problem. Please notice the welcome message you see after connect using console doesn't represent the version of Nebula service. That's the version of your console. I'd recommend you to check your service version and make sure it is up to date.
> 
> ![Screen Shot 2021-03-05 at 12 02 02 PM](https://user-images.githubusercontent.com/18348405/110065639-9a34dc80-7daa-11eb-930d-d28cacc3ff17.png)

I'm very sure，I download nebula verison：nebula-graph-2.0.0-rc1.el7.x86_64.rpm
github link： https://github.com/vesoft-inc/nebula-graph/releases
This one release not OK ？

**Comment by Aiee** [comment]
1. To check the version of Nebula service, you may input ```show hosts graph``` in the console and a ```Git Info Sha``` will be returned. We are working to make it easier to get version info.
2. The collect() feature was added after the RC1 release, please use the nightly release if you need to use this function
3. Github issue is mainly used to report the problems with the newest release, so I'm closing this issue.

The best place to get help with Nebula is the official forum. The Dev team and other users in the community are there to help.
Forum link: English https://discuss.nebula-graph.io/. Chinese https://discuss.nebula-graph.com.cn/

**Comment by Aiee** [comment]
1. To check the version of Nebula service, you may input ```show hosts graph``` in the console and a ```Git Info Sha``` will be returned. We are working to make it easier to get version info.
2. The collect() feature was added after the RC1 release, please use the nightly release if you need to use this function
3. Github issue is mainly used to report the problems with the newest release, so I'm closing this issue.

The best place to get help with Nebula is the official forum. The Dev team and other users in the community are there to help.
Forum link: English https://discuss.nebula-graph.io/. Chinese https://discuss.nebula-graph.com.cn/
