### ISSUE TITLE
[opencypher compatibility][bug] keywords recognize error

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#823]
![image](https://user-images.githubusercontent.com/50101159/111303574-a31d8c00-868f-11eb-8261-63a07f89f091.png)

![image](https://user-images.githubusercontent.com/50101159/111303590-a749a980-868f-11eb-8704-c69376843e54.png)

**Comment by CPWstatic** [comment]
If you need a `set` as a column name, try it this way
```
return 1 as `set`
```
