### ISSUE TITLE
[bug] something wrong with the backslash

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#824]
![image](https://user-images.githubusercontent.com/50101159/111306316-08bf4780-8693-11eb-8d03-4b0d9ee4a2cb.png)

```
 LOOKUP ON player WHERE player.name == "Tony Parker" | GO FROM $-.VertexID over follow WHERE follow.degree != reduce(totalNum = 5, n IN range(1, 3) | $$.player.age + totalNum + n)  YIELD $$.player.name AS id, $$.player.age AS age, follow.degree AS degree
```

if I add backslash

![image](https://user-images.githubusercontent.com/50101159/111306469-30161480-8693-11eb-9187-e207449893d6.png)

![image](https://user-images.githubusercontent.com/50101159/111306452-28567000-8693-11eb-8f79-ee89c85845ff.png)

**Comment by czpmango** [comment]
Could you raise issues without using pictures, it's better to use markdown.

**Comment by whitewum** [comment]
```
LOOKUP ON player WHERE player.name == "Tony Parker" |  \
GO FROM $-.VertexID over follow \
WHERE follow.degree != reduce(totalNum = 5, n IN range(1, 3) | $$.player.age + totalNum + n) \
YIELD $$.player.name AS id, $$.player.age AS age, follow.degree AS degree
```

**Comment by whitewum** [comment]
I think the problem is that pipe symbol in reduce()

**Comment by HarrisChu** [comment]
not repeat in v2.0.1

**Comment by CPWstatic** [comment]
Please upgrade the nebula-consle to a latest version.
