### ISSUE TITLE
Cannot create a space on a GROUP when the GROUP exists

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#835]
Created a space nba2:
![image](https://user-images.githubusercontent.com/69501902/111589062-548eff80-87ff-11eb-84a7-647467be4744.png)

SHOW CREATE SPACE nba2:
![image](https://user-images.githubusercontent.com/69501902/111589124-6a042980-87ff-11eb-96c5-542721c89847.png)

Related issue:
https://github.com/vesoft-inc/nebula-graph/issues/821

**Comment by darionyaphet** [comment]
duplicate with 821
