### ISSUE TITLE
[bug] is itlegal to reference a not exist property (a.k.a property name typo)

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#869]
```
match (s1:stocks )-[e:relation]->(s2:stocks) where e.weight > 0.1 return s1.name, e.weight, s2.name
```

I should type `e.weight` but typo `e.weigth`

the return column of `e.weigth` is __NULL__. 

When I create the edge, I set relation.weight NOT NULL. 

SO I confuse a sec, and find out that typo.

But, Is it legal to return a not existed alias or property name?

**Comment by CPWstatic** [comment]
As far as i known, it's legal in openCypher/neo4j.

**Comment by HarrisChu** [comment]
https://discuss.nebula-graph.com.cn/t/topic/4413

It's difficult to find the typo error in a complex query, and the result data set may be confused.

```
# e.harris is NULL, so these is no data set.
(root@nebula) [nba]>  match (v:player)- [e] -() where e.harris > 1   return v  limit 1
Empty set (time spent 10305/19358 us)

Tue, 15 Jun 2021 14:21:09 CST
```

**Comment by CPWstatic** [comment]
As I replied earlier that it's legal in openCypher/neo4j. I'll close this issue first, let us know if you have a further concern.
