### ISSUE TITLE
[OpenCypher compatibility] substring() with index 0 returns the whole string

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#879]
Function: substring(string a, int pos, int count)
nGQL: RETURN substring("Hello, Nebula", 0, 2)

In openCypher, if `pos` is 0, the substring will start at the beginning of `a`.
But nGQL returns the whole string `a`.
![image](https://user-images.githubusercontent.com/69501902/112455016-478c8600-8d94-11eb-9ce9-672fd8e1fcc8.png)
![image](https://user-images.githubusercontent.com/69501902/112455052-507d5780-8d94-11eb-8665-ee4730c6dc56.png)

**Comment by nevermore3** [comment]
https://github.com/vesoft-inc/nebula-common/pull/491
