### ISSUE TITLE
Using a negative number as the index for substring() returns BAD_DATA

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#880]
RETURN substring("Hello, Nebula", -1, 2)

![image](https://user-images.githubusercontent.com/69501902/112461675-23807300-8d9b-11eb-9e2c-e5800bb34571.png)

OpenCypher returns an error:

![image](https://user-images.githubusercontent.com/69501902/112461895-65111e00-8d9b-11eb-8938-b46608b304dc.png)

Logically it should at least start counting from the last character of the string. BAD_DATA is so odd.

**Comment by czpmango** [comment]
```
neo4j@neo4j> return substring("Hello, Nebula",-1,2);
null
neo4j@neo4j> return substring("Hello, Nebula",1,2);
+--------------------------------+
| substring("Hello, Nebula",1,2) |
+--------------------------------+
| "el"                           |
+--------------------------------+

```

**Comment by czpmango** [comment]
Do not submit an issue with pictures. @randomJoe211 
You could refer to [https://github.com/vesoft-inc/nebula-graph/issues/948](https://github.com/vesoft-inc/nebula-graph/issues/948)

**Comment by Shylock-Hg** [comment]
Same with #935
