### ISSUE TITLE
Backfill \0 to the WHERE clause when query for FIXED_LENGTH fields is performed

### ISSUE THREAD

**Issue by jamieliu1023** [vesoft-inc/nebula-graph#914]
This is an issue brought up by an overseas user in Slack. Quote him:

"When doing WHERE queries against FIXED_STRING fields I need to include repeated '\0' after my query up to the length of the fixed string in order for any results to be returned, surely this shouldn't be required? This isn't a necessity when using those same fields in a LOOKUP query, it only affects unindexed WHERE clauses. i.e. if I have a fixed string of length 5, the query where x == "val" returns nothing, whereas where x == "val\0\0" returns the expected result set."

**Comment by HarrisChu** [comment]
cannot repeat this bug in v2.0.1
need mote infomation

**Comment by jamieliu1023** [comment]
What specific information is needed? I could ask the user to update info accordingly.

**Comment by HarrisChu** [comment]
1. nebula version 
2. space & tag & index schema
3. the insert statement
4. query statement

**Comment by CPWstatic** [comment]
How is it going for this issue?

**Comment by jamieliu1023** [comment]
You may just close it because the user didn't manage to provide the information needed.
