### ISSUE TITLE
[openCypher compatibility] The timestamp function returns a different output

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#934]
openCypher/nGQL: RETURN timestamp()

openCypher output:
![image](https://user-images.githubusercontent.com/69501902/113981457-48d0af00-987a-11eb-9aea-c0d55b4e77a9.png)

nGQL output:
![image](https://user-images.githubusercontent.com/69501902/113981510-56863480-987a-11eb-8065-c2ec21ad16e8.png)

openCypher/nGQL: RETURN timestamp()

**Comment by Shylock-Hg** [comment]
@vesoft-inc/nebula-force I remember someone had fix it.Plz attach the PR.
