### ISSUE TITLE
YIELD with a dot in a result of query

### ISSUE THREAD

**Issue by avently** [vesoft-inc/nebula-graph#942]
Got unexpected behavior (maybe just for me). For some reason I can't receive a column (via YIELD) with a dot inside it's name.
Example:
```ngql
GO FROM "id" OVER some_edge YIELD $$.wallet.type as wallet.type

Syntax error near .type
```

However this one works:
```ngql
GO FROM "id" OVER some_edge YIELD $$.wallet.type as type
```

Could you, please, make such possibility to have a column with the dot in it's name?
The reason why I want to use it in such way because it helps me to unify all responses I get from database for easy parsing. So I have a class transformers in nodejs which expects to see a column name like class.property. This way I can easily transform any database response to js object without relying on column index

(I know that I can pipe response from go from, get the _dst and make "fetch prop on" on it but it probably worse in performance than to get it right from the first query.)

**Comment by jievince** [comment]
I think such an alias `a.b` is easy to confuse with `schema.prop`. It's not clear.  Why not name it as `wallet_type`?

**Comment by avently** [comment]
@jievince 
> Why not name it as wallet_type ?

This is how i'll do if the idea of this issue is rejected. But it's not as easy to use as tag.property.
And also notice that by default YIELD returns something like:

```ngql

... YIELD profile.name, profile.email
```
Which will look like profile.name and profile.email. If I choose profile_name and profile_email I need to rewrite all queries and paste this unneded words like `profile.name as profile_name...`

Also some people probably use tags with underscore like order_book. Adding a property to it like `order_book_ask_price` will make it so hard to read and maintain. But `order_book.ask_price` is much better.

Anyway if it's not hard to implement and will not hurt performance why not to implement? Less places for user's errors

**Comment by avently** [comment]
@jievince please, let me know what you and the team decided for this issue. If it's not gonna be implemented you can close the issue.

**Comment by jievince** [comment]
@avently Hi avently, thank you for your detailed explanation of your usage scenario. But I think it's hard for the parser in our implementation to distinguish between an alias `a.b` and a prop of a tag/edge `a.b`. And in order to keep consistency with cypher, we're not going to fulfill this feature.

**Comment by avently** [comment]
@jievince yep, understood. Performance is much more important. Thank you for quick answer
