### ISSUE TITLE
UPDATE and UPSERT mix up properties of different tags or edge types in the WHEN clause

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#992]
Given a vertex with VID `"player100"`, tag `player`, property `name`=`"Tim Duncan"`

And another tag `player_with_default2(name string DEFAULT "hello", age int DEFAULT 20)`

When executing `UPSERT VERTEX ON player_with_default2 "player100" SET age = age + 1 WHEN name == "Tim Duncan" YIELD name AS Name, age AS Age;`, the `WHEN` condition should not be met since on tag `player_with_default2` the vertex `"player100"` has no `name` property.

But the result is as follows:

```ngql
nebula> UPSERT VERTEX ON player_with_default2 "player100" SET age = age + 1 WHEN name == "Tim Duncan" YIELD name AS Name, age AS Age;

+---------+-----+
| Name    | Age |
+---------+-----+
| "hello" | 21  |
+---------+-----+
Got 1 rows (time spent 2253/2911 us)
```

This is not right. Please check it out. Probably `UPDATE` has the same issue.

**Comment by randomJoe211** [comment]
Update:

Maybe the `WHEN` clause does not take effect at all when the vertex or edge does not exist.

**Comment by panda-sheep** [comment]
1) The `when `condition is always true during `upsert`
2) When `update`, the `when` condition takes effect

**Comment by panda-sheep** [comment]
I think there is no problem
